/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['SignUpCommand'];
          'text/json': components['schemas']['SignUpCommand'];
          'application/*+json': components['schemas']['SignUpCommand'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthResultDto'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ValidationProblemDetails'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['LogInCommand'];
          'text/json': components['schemas']['LogInCommand'];
          'application/*+json': components['schemas']['LogInCommand'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthResultDto'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me/plan': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ChangePlanRequest'];
          'text/json': components['schemas']['ChangePlanRequest'];
          'application/*+json': components['schemas']['ChangePlanRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserDto'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/device/pair': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['PairDeviceCommand'];
          'text/json': components['schemas']['PairDeviceCommand'];
          'application/*+json': components['schemas']['PairDeviceCommand'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PairResultDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/device/heartbeat': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['HeartbeatRequest'];
          'text/json': components['schemas']['HeartbeatRequest'];
          'application/*+json': components['schemas']['HeartbeatRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeviceStatusDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/device/groups': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['GroupsRequest'];
          'text/json': components['schemas']['GroupsRequest'];
          'application/*+json': components['schemas']['GroupsRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': number;
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/device/jobs/claim': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['JobDto'];
          };
        };
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': unknown;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/device/jobs/{postId}/result': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          postId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ResultRequest'];
          'text/json': components['schemas']['ResultRequest'];
          'application/*+json': components['schemas']['ResultRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PostDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/device/media/{mediaId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          mediaId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': unknown;
            'application/octet-stream': unknown;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/devices': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeviceDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/devices/pairing': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PairingCodeDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/devices/{deviceId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
          deviceId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': unknown;
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/engine': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['EngineSettingsDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/engine/anti-ban': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AntiBanDto'];
          'text/json': components['schemas']['AntiBanDto'];
          'application/*+json': components['schemas']['AntiBanDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['EngineSettingsDto'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/engine/offline': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['OfflineDto'];
          'text/json': components['schemas']['OfflineDto'];
          'application/*+json': components['schemas']['OfflineDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['EngineSettingsDto'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/engine/extension': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ExtensionStateRequest'];
          'text/json': components['schemas']['ExtensionStateRequest'];
          'application/*+json': components['schemas']['ExtensionStateRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ExtensionStateDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/engine/waiting/skip': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ExtensionStateDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/media': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MediaDto'][];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'multipart/form-data': {
            file?: components['schemas']['IFormFile'];
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MediaDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/media/{mediaId}/content': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
          mediaId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': unknown;
            'application/octet-stream': unknown;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/snippets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SnippetDto'][];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateSnippetRequest'];
          'text/json': components['schemas']['CreateSnippetRequest'];
          'application/*+json': components['schemas']['CreateSnippetRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SnippetDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
        };
        header?: never;
        path: {
          wsId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PostDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/posts/schedule': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ScheduleRequest'];
          'text/json': components['schemas']['ScheduleRequest'];
          'application/*+json': components['schemas']['ScheduleRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ScheduleResultDto'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ValidationProblemDetails'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/posts/{postId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
          postId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': unknown;
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/posts/{postId}/retry': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
          postId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PostDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/posts/{postId}/dismiss': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
          postId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PostDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/errors': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PostDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkspaceDto'][];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateWorkspaceRequest'];
          'text/json': components['schemas']['CreateWorkspaceRequest'];
          'application/*+json': components['schemas']['CreateWorkspaceRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkspaceDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/accounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AccountDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{wsId}/accounts/{accountId}/reconnect': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          wsId: string;
          accountId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AccountDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AccountDto: {
      /** Format: uuid */
      id: string;
      platform: components['schemas']['Platform'];
      name: string;
      handle: string;
      defaultTarget: string;
      health: components['schemas']['AccountHealth'];
      groups: string[];
      connected: boolean;
    };
    /** @enum {unknown} */
    AccountHealth: 'ok' | 'warn' | 'relogin';
    AntiBanDto: {
      /** Format: int32 */
      min: number;
      /** Format: int32 */
      max: number;
      limits: components['schemas']['PlatformLimitsDto'];
      typing: boolean;
      scroll: boolean;
      shuffle: boolean;
      autoPause: boolean;
      warmup: boolean;
    };
    AuthResultDto: {
      token: string;
      /** Format: date-time */
      expiresAt: string;
      user: components['schemas']['UserDto'];
    };
    ChangePlanRequest: {
      plan: components['schemas']['PlanKey'];
    };
    CreateSnippetRequest: {
      title: string;
      text: string;
    };
    CreateWorkspaceRequest: {
      name: string;
    };
    DeviceDto: {
      /** Format: uuid */
      id: string;
      name: string;
      browser: string;
      version: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      lastSeenAt: null | string;
      online: boolean;
      /** Format: uuid */
      accountId: null | string;
    };
    DeviceStatusDto: {
      /** Format: uuid */
      deviceId: string;
      deviceName: string;
      /** Format: uuid */
      workspaceId: string;
      workspaceName: string;
      /** Format: uuid */
      accountId: null | string;
      /** Format: int32 */
      groups: number;
      online: boolean;
      antiBan: components['schemas']['AntiBanDto'];
    };
    EngineSettingsDto: {
      antiBan: components['schemas']['AntiBanDto'];
      offline: components['schemas']['OfflineDto'];
      extensionOnline: boolean;
      simulatedOffline: boolean;
      /** Format: int32 */
      devices: number;
      /** Format: int32 */
      devicesOnline: number;
    };
    ExtensionStateDto: {
      online: boolean;
      /** Format: int32 */
      affected: number;
    };
    ExtensionStateRequest: {
      online: boolean;
    };
    /** @enum {unknown} */
    FailureCode:
      | 'rate_limit'
      | 'session'
      | 'network'
      | 'pending_approval'
      | 'media_too_large'
      | 'quota'
      | null;
    GroupLinkDto: {
      name: string;
      url: string;
    };
    GroupsRequest: {
      groups: components['schemas']['GroupLinkDto'][];
    };
    HeartbeatRequest: {
      version: null | string;
    };
    /** Format: binary */
    IFormFile: string;
    JobDto: {
      /** Format: uuid */
      postId: string;
      groupName: string;
      groupUrl: string;
      content: string;
      media: components['schemas']['JobMediaDto'][];
      antiBan: components['schemas']['AntiBanDto'];
    };
    JobMediaDto: {
      /** Format: uuid */
      id: string;
      name: string;
      contentType: string;
    };
    LogInCommand: {
      email: string;
      password: string;
    };
    MediaDto: {
      /** Format: uuid */
      id: string;
      name: string;
      contentType: string;
      kind: components['schemas']['MediaKind'];
      /** Format: int64 */
      size: number;
      /** Format: int32 */
      usedCount: number;
      /** Format: date-time */
      createdAt: string;
    };
    /** @enum {unknown} */
    MediaKind: 'image' | 'video';
    OfflineDto: {
      policy: components['schemas']['OfflinePolicy'];
      window: string;
      line: boolean;
      email: boolean;
      push: boolean;
    };
    /** @enum {unknown} */
    OfflinePolicy: 'skip' | 'queue' | 'notify';
    PairDeviceCommand: {
      code: string;
      name: string;
      browser: null | string;
      version: null | string;
    };
    PairingCodeDto: {
      code: string;
      /** Format: date-time */
      expiresAt: string;
      /** Format: int32 */
      maxDevices: null | number;
    };
    PairResultDto: {
      deviceKey: string;
      /** Format: uuid */
      deviceId: string;
      deviceName: string;
      /** Format: uuid */
      workspaceId: string;
      workspaceName: string;
      /** Format: uuid */
      accountId: string;
    };
    /** @enum {unknown} */
    PlanKey: 'free' | 'basic' | 'pro' | 'agency';
    /** @enum {unknown} */
    Platform: 'fb' | 'x' | 'ig' | 'tt' | 'line' | 'th';
    PlatformLimitsDto: {
      /** Format: int32 */
      fb: number;
      /** Format: int32 */
      x: number;
      /** Format: int32 */
      ig: number;
      /** Format: int32 */
      tt: number;
      /** Format: int32 */
      line: number;
      /** Format: int32 */
      th: number;
    };
    PostDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      accountId: string;
      platform: components['schemas']['Platform'];
      target: string;
      content: string;
      mediaIds: string[];
      /** Format: date-time */
      scheduledAt: string;
      status: components['schemas']['PostStatus'];
      failureCode: null | components['schemas']['FailureCode'];
      failureDetail: null | string;
      /** Format: date-time */
      publishedAt: null | string;
    };
    /** @enum {unknown} */
    PostStatus: 'queued' | 'posting' | 'success' | 'failed' | 'skipped' | 'pending' | 'waiting';
    ProblemDetails: {
      type?: null | string;
      title?: null | string;
      /** Format: int32 */
      status?: null | number;
      detail?: null | string;
      instance?: null | string;
    };
    ResultRequest: {
      ok: boolean;
      awaitingApproval: boolean;
      needsLogin: boolean;
      blocked: boolean;
      error: null | string;
    };
    ScheduleRequest: {
      content: string;
      mediaIds: null | string[];
      /** Format: date-time */
      startAt: string;
      useDelay: boolean;
      repeat: string;
      targets: components['schemas']['TargetSelection'][];
    };
    ScheduleResultDto: {
      /** Format: int32 */
      created: number;
      /** Format: date-time */
      firstAt: string;
      /** Format: date-time */
      lastAt: string;
    };
    SignUpCommand: {
      email: string;
      password: string;
      name: null | string;
      plan: null | components['schemas']['PlanKey'];
    };
    SnippetDto: {
      /** Format: uuid */
      id: string;
      title: string;
      text: string;
      /** Format: int32 */
      usedCount: number;
    };
    TargetSelection: {
      /** Format: uuid */
      accountId: string;
      groups: null | string[];
    };
    UserDto: {
      /** Format: uuid */
      id: string;
      email: string;
      name: string;
      role: components['schemas']['UserRole'];
      plan: components['schemas']['PlanKey'];
    };
    /** @enum {unknown} */
    UserRole: 'user' | 'admin';
    ValidationProblemDetails: {
      type?: null | string;
      title?: null | string;
      /** Format: int32 */
      status?: null | number;
      detail?: null | string;
      instance?: null | string;
      errors?: {
        [key: string]: string[];
      };
    };
    WorkspaceDto: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: int32 */
      posts7: number;
      /** Format: int32 */
      members: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
